ferry . services accessoires:
  question: Allez-vous profiter des restaurants, bars et divers loisirs ?
  description: |
    Par exemple, la piscine, le jacuzzi, les machines Ã  jeu, les magasins de souvenir style "duty-free", etc.

    Nous considÃ©rons ici que si vous ne profitez pas de ces services accessoires, leur empreinte ne vous est pas attribuÃ©e.

    Notons que ces services peuvent Ãªtre jugÃ©s "nÃ©cessaires" par certains, mais que Ã§a dÃ©pend Ã©normÃ©ment de la personne. 

    Pour une traversÃ©e d'une nuit de plus de 350km (Marseille-Ajaccio), on peut tout Ã  fait se passer de restaurant. On trouvera souvent Ã  quai des boulangeries ou restaurants, et il est tout Ã  fait possible de manger sur le pont au moins l'Ã©tÃ©. C'est clairement une question de confort, dont certains ne veulent pas se passer.
  note: |
    Il s'agira dans un second temps de faire la part des choses entre toutes ces possibilitÃ©s aux implications bien diffÃ©rentes : on peut craindre qu'une piscine pÃ¨se trÃ¨s lourd.
  icÃ´nes: ğŸ½ğŸº
  par dÃ©faut: oui

